
build-whisper-cpp-dev-ubuntu-20-04:
	podman build -t whisper-cpp-dev -f whisper-cpp-dev

run-whisper-cpp-dev-ubuntu-20-04:
	podman run -it whisper-cpp-dev

build-whisper-cpp-arm-mac-22-04:
	podman build -t whisper-cpp-arm -f whisper-cpp-arm-macos

run-whisper-cpp-arm-mac-22-04:
	podman run -it whisper-cpp-arm
