
download-model:
	@mkdir -p models
	wget https://github.com/intel/openvino-rs/raw/main/crates/openvino/tests/fixtures/mobilenet/mobilenet.xml -O models/mobilenet.xml
	wget https://github.com/intel/openvino-rs/raw/main/crates/openvino/tests/fixtures/mobilenet/mobilenet.bin -O models/mobilenet.bin
