
download-model:
	@mkdir -p models
	wget https://github.com/intel/openvino-rs/raw/main/crates/openvino/tests/fixtures/mobilenet/mobilenet.xml -O models/mobilenet.xml
	wget https://github.com/intel/openvino-rs/raw/main/crates/openvino/tests/fixtures/mobilenet/mobilenet.bin -O models/mobilenet.bin
	#wget https://github.com/intel/openvino-rs/blob/main/crates/openvino/tests/fixtures/mobilenet/tensor-1x224x224x3-f32.bgr -O models/tensor-1x224x224x3-f32.bgr
