.PHONY: download-model
download-model:
	@mkdir -p models 
	@cd models && curl -LO https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/resolve/5db6994dca7288297c59693b5e27b62f22a54e1f/llama-2-7b-chat.Q4_0.gguf
		
