name: Main Branch Commit Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ggml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Building ggml examples
        run: |
          echo "Build ggml examples"
          cd fundamentals/ggml
          git submodule update --init ggml
          make ggml-init
          make ggml
          make

  llama_cpp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Building llama.cpp examples
        run: |
          cd fundamentals/llama.cpp
          git submodule update --init llama.cpp
          make llama-init
          make llama
          make all
